# Generated by Django 3.2.4 on 2022-03-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flan',
            name='sugar_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flan',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
    ]
